# Site settings
title:          a.min.blog
description:    "personal blog"
baseurl:        "/blog"
url:            "https://davide2894.github.io/blog"

# Author
author:         
  name:         Davide Iaiunese
  url:          https://github.com/davide2894
  email:        davide.iaiunese@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
