# Site settings
title:          Morning Dev
description:    "chronicles of my coding journey"
baseurl:        "/morning-dev" # does not include hostname
url:            "https://davide2894.github.io"

# Author       
author:
  name:         Davide Iaiunese
  url:          https://github.com/davide2894bas
  email:        davide.iaiunese@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
