# Site settings
title:          a loaf of code
description:    "your regular dev"
baseurl:        "_site/" # does not include hostname

# Author       
  name:         Davide Iaiunese
  url:          https://github.com/davide2894
  email:        davide.iaiunese@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
